# Generated by Django 4.2.1 on 2023-06-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_useraccount_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(default='image', upload_to='profilePicture'),
            preserve_default=False,
        ),
    ]
